url = https://www.flipkart.com/

browserstack.username=annamalairajalin_6UIPGV
browserstack.accesskey=p6Leeyhx1SpAiLwMTRwD

browserstack.hub.url = "https://hub-cloud.browserstack.com/wd/hub";

is.cloud = true

execution.mode = local


